language: en
early_access: false
reviews:
  profile: ai
  request_changes_workflow: true
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    exclude:
      - "**/node_modules/**"
      - "**/build/**"
      - "**/dist/**"
      - "**/release/**"
      - "**/.git/**"
      - "**/third_party/**"
      - "**/bin/**"
      - "ui/node_modules/**"
      - "ui/release/**"
    include:
      - "src/**"
      - "ui/src/**"
chat:
  auto_reply: true
categories:
  snapshot:
    paths: []
  security:
    paths: []
  test_coverage:
    paths: []
knowledge:
  base_path: .
  use_website: true
rules:
  ai:
    prompt:
      - "@coderabbitai explain"
      - "@coderabbitai summarize"