language: en
early_access: false
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!**/node_modules/**"
    - "!**/build/**"
    - "!**/dist/**"
    - "!**/release/**"
    - "!**/.git/**"
    - "!**/third_party/**"
    - "!**/bin/**"
    - "!ui/node_modules/**"
    - "!ui/release/**"
    - ".coderabbit.yaml"
    - "package.json"
    - "package-lock.json"
    - "ui/package.json"
    - "ui/package-lock.json"
    - "src/**"
    - "ui/src/**"
chat:
  auto_reply: true
